### ISSUE TITLE
Configuration file missing when setting up validator node

### ISSUE THREAD

**Issue by jprupp** [Sifchain/sifchain-validators#69]
When reaching [this step](https://github.com/Sifchain/sifchain-validators/blob/master/docs/nodes/setup/standalone/manual.md#archive-node-1) of the manual setup instructions, I get this error:

```
1:41PM ERR failed to read
  error="lstat /srv/sifnode/.sifnoded/cosmovisor/current/upgrade-info.json: no such file or directory" 
  filename=/srv/sifnode/.sifnoded/cosmovisor/current/upgrade-info.json module=cosmovisor
```

I don't think any of the prior steps provides this configuration file.

**Comment by jprupp** [comment]
The [snapshot step](https://github.com/Sifchain/sifchain-validators/blob/master/docs/nodes/setup/standalone/manual.md#snapshot) didn't work for me either:

```
sifnode@hera:~/.sifnoded/data$ wget -O sifchain.tar http://135.181.60.250:8081/sifchain/"${snapshot}"
--2022-04-20 10:57:08--  http://135.181.60.250:8081/sifchain/sifchain-1_2022-04-20.tar
Connecting to 135.181.60.250:8081... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-20 10:57:08 ERROR 404: Not Found.
```

**Comment by intl-man** [comment]
> When reaching [this step](https://github.com/Sifchain/sifchain-validators/blob/master/docs/nodes/setup/standalone/manual.md#archive-node-1) of the manual setup instructions, I get this error:
> 
> ```
> 1:41PM ERR failed to read
>   error="lstat /srv/sifnode/.sifnoded/cosmovisor/current/upgrade-info.json: no such file or directory" 
>   filename=/srv/sifnode/.sifnoded/cosmovisor/current/upgrade-info.json module=cosmovisor
> ```
> 
> I don't think any of the prior steps provides this configuration file.

As discussed, this is not actually an issue.

**Comment by intl-man** [comment]
> The [snapshot step](https://github.com/Sifchain/sifchain-validators/blob/master/docs/nodes/setup/standalone/manual.md#snapshot) didn't work for me either:
> 
> ```
> sifnode@hera:~/.sifnoded/data$ wget -O sifchain.tar http://135.181.60.250:8081/sifchain/"${snapshot}"
> --2022-04-20 10:57:08--  http://135.181.60.250:8081/sifchain/sifchain-1_2022-04-20.tar
> Connecting to 135.181.60.250:8081... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2022-04-20 10:57:08 ERROR 404: Not Found.
> ```

Looks like the name of the snapshots has changed. This has been updated in the documentation.
